name: Run Vinted searches

on:
  schedule:
    - cron: '0/15 7-22 * * *'
  workflow_dispatch:

jobs:
  run_searches:
    name: Run Vinted Searches
    env: 
      API_TOKEN: ${{ secrets.API_TOKEN }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run searches and update seen listings 
        run: |
          python main.py
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add 'seen_listings.txt' || true
          git commit -m "Updated seen listings file" || true
          git push origin master || true